//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChuyenBay.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyChuyenBayEntities : DbContext
    {
        public QuanLyChuyenBayEntities()
            : base("name=QuanLyChuyenBayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuyenBay> ChuyenBays { get; set; }
        public virtual DbSet<SanBay> SanBays { get; set; }
        public virtual DbSet<TuyenBay> TuyenBays { get; set; }
    }
}
