//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChuyenBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanBay
    {
        public string MaSanBay { get; set; }
        public string TenSanBay { get; set; }
        public string TinhThanh { get; set; }
    }
}
